name: Branch

on: 
  push:
    branches-ignore: 
      - master

jobs:

  Build_and_Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag aci_appliance_server_branch:latest

    - name: Test the execution of the Playbook but don't make any changes
      run: docker run --rm aci_appliance_server_branch:latest ansible-playbook -i inventory aci_appliance_server.yml -v --check --diff
