name: Production

on: 
  push:
    branches:
      - master

jobs:

  Build_and_Deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag ignw/dc_2020_aci_appliance_server_production:latest

    - name: Run the playbook
      run: docker run --rm ignw/dc_2020_aci_appliance_server_production:latest ansible-playbook -i inventory aci_appliance_server.yml -v